# Generated by Django 3.1.7 on 2021-08-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210823_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userFollowers',
            new_name='userFollowing',
        ),
    ]
